apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8aui
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-8aui@sha256:9bdf3222461b36bb44a4b71efd2a126c5fc4405c3dcdd3cdb55e86146c1e8604
        name: my-nodejs
        resources: {}
status: {}
